# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Install JFrog CLI
          command: 
            curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Configure JFrog CLI
          command: 
            ./jfrog rt config server1 --url=https://jfrogtestusw2.jfrog.io/artifactory --user=a_amith --password=fAk3L5uWIs
      - run:
          name: Running the build
          command: 
            ./jfrog rt gradlec --server-id-resolve=server1 --server-id-deploy=server1 --repo-resolve=gradle-gradle-dev --repo-deploy=gradle-gradle-dev --use-wrapper=true --uses-plugin=true
      - run:
          name: Gradle Clean
          command:
            ./jfrog rt gradle clean artifactoryPublish --build-name=gradle-circleci --build-number=${CIRCLE_BUILD_NUM}
      - run:
          name: Set Properties
          command:       
            ./jfrog rt sp "gradle-release/GitLab-Gradle-Minimal/1.0-SNAPSHOT/GitLab-Gradle-Minimal-1.0-SNAPSHOT.jar" "artifacts=artifactory"
      - run:
          name: Collect Environment
          command:      
            ./jfrog rt bce gradle-circleci ${CIRCLE_BUILD_NUM}
      - run:
          name: Build Publish
          command:
            ./jfrog rt bp gradle-circleci ${CIRCLE_BUILD_NUM}
